#!/usr/bin/env bash

set -e

HOURS=$1
DIR=$(dirname $0)
KEY=$DIR/id_rsa

if [ -z $HOURS ]; then
  HOURS=1
fi

/usr/bin/ssh-add -D
/usr/bin/ssh-add -t ${HOURS}H $KEY

DEV=$(df -k "$0" | tail -1 | awk '{ print $1 }')
echo $DEV

echo '#!/bin/sh -xv' >/tmp/udisk.tmp
echo "sudo umount $DEV" >>/tmp/udisk.tmp
cat /tmp/udisk.tmp
chmod +x /tmp/udisk.tmp

/tmp/udisk.tmp & 
